from datetime import date, timedelta
import random


def generate_samples(
    ddl_day: date,
    num_layers: int,
    branching_range: tuple = (1, 3),
) -> list:
    """Generate a layered branching supply network with day-level windows.

    Layer 0 is the destination node. Upstream layers are generated by
    backtracking from each downstream node's deadline.
    """
    if num_layers < 0:
        return []
    min_b, max_b = branching_range
    if min_b < 1 or max_b < min_b:
        raise ValueError("branching_range must satisfy 1 <= min <= max")

    nodes = []
    node_id_counter = 0

    # Layer 0 destination node.
    root = {
        "node_id": node_id_counter,
        "layer_id": 0,
        "parent_id": None,
        "start_day": ddl_day,
        "end_day": ddl_day,
        "load_days": 0,
        "transit_days": 0,
    }
    nodes.append(root)
    current_layer_nodes = [root]
    node_id_counter += 1

    # Build upstream layers: 1..num_layers
    for layer_id in range(1, num_layers + 1):
        next_layer_nodes = []
        for parent in current_layer_nodes:
            parent_deadline = parent["end_day"]
            num_parents = random.randint(min_b, max_b)

            for _ in range(num_parents):
                load_days = random.randint(1, 4)
                transit_days = random.randint(1, 7)
                window_days = random.randint(1, 5)

                # Latest feasible departure day for this upstream node.
                end_day = parent_deadline - timedelta(days=load_days + transit_days)
                start_day = end_day - timedelta(days=window_days)

                assert start_day <= end_day
                assert end_day + timedelta(days=load_days + transit_days) <= parent_deadline

                node = {
                    "node_id": node_id_counter,
                    "layer_id": layer_id,
                    "parent_id": parent["node_id"],
                    "start_day": start_day,
                    "end_day": end_day,
                    "load_days": load_days,
                    "transit_days": transit_days,
                }
                nodes.append(node)
                next_layer_nodes.append(node)
                node_id_counter += 1

        current_layer_nodes = next_layer_nodes

    return nodes
