# Generated by Django 5.2.7 on 2025-10-07 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=200)),
                ('case_description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200)),
                ('material_description', models.TextField()),
                ('quantity', models.IntegerField(default=0)),
                ('date_req', models.DateTimeField(verbose_name='date required')),
                ('criticality', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=200)),
                ('component_description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('case_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainDash.case_system')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200)),
                ('Lat', models.FloatField(default=0, max_length=20)),
                ('Lon', models.FloatField(default=0, max_length=20)),
                ('country', models.CharField(default='', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('NAIC_code', models.CharField(default='', max_length=6)),
                ('HS_code', models.CharField(default='', max_length=6)),
                ('production_time_days', models.IntegerField(default=0)),
                ('shipping_time_days', models.IntegerField(default=0)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainDash.component')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200)),
                ('Lat', models.FloatField(default=0, max_length=20)),
                ('Lon', models.FloatField(default=0, max_length=20)),
                ('country', models.CharField(default='', max_length=100)),
                ('quality', models.IntegerField(default=0)),
                ('delay_risk', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('NAIC_code', models.CharField(default='', max_length=6)),
                ('HS_code', models.CharField(default='', max_length=6)),
                ('production_time_days', models.IntegerField(default=0)),
                ('shipping_time_days', models.IntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainDash.material')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=200)),
                ('part_description', models.TextField()),
                ('part_number', models.CharField(default='', max_length=100)),
                ('date_req', models.DateTimeField(verbose_name='date required')),
                ('criticality', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('NAIC_code', models.CharField(default='', max_length=6)),
                ('HS_code', models.CharField(default='', max_length=6)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainDash.component')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainDash.part'),
        ),
        migrations.CreateModel(
            name='PartSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200)),
                ('Lat', models.FloatField(default=0, max_length=20)),
                ('Lon', models.FloatField(default=0, max_length=20)),
                ('country', models.CharField(default='', max_length=100)),
                ('quality', models.IntegerField(default=0)),
                ('delay_risk', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('NAIC_code', models.CharField(default='', max_length=6)),
                ('HS_code', models.CharField(default='', max_length=6)),
                ('production_time_days', models.IntegerField(default=0)),
                ('shipping_time_days', models.IntegerField(default=0)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainDash.part')),
            ],
        ),
    ]
