# Generated by Django 5.2.7 on 2026-02-25

from django.db import migrations


class Migration(migrations.Migration):
    # Legacy migrations 0002..0010 targeted removed historical models (Item/Supplier/Industry).
    # This replacement keeps migration history consistent for current schema branches.
    replaces = [
        ("mainDash", "0002_supplier_supplieritem_item_criticality_and_more"),
        ("mainDash", "0003_supplier_location"),
        ("mainDash", "0004_item_naics_code_item_quantity_supplier_delay_risk_and_more"),
        ("mainDash", "0005_coordenadas"),
        ("mainDash", "0006_supplier_lat_supplier_lon"),
        ("mainDash", "0007_coordenadas_supplier"),
        ("mainDash", "0008_alter_coordenadas_supplier"),
        ("mainDash", "0009_alter_coordenadas_supplier"),
        ("mainDash", "0010_alter_coordenadas_supplier"),
    ]

    dependencies = [
        ("mainDash", "0001_initial"),
    ]

    operations = []
