# Generated by Django 4.2.4 on 2023-08-04 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainDash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200)),
                ('naics_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.DateTimeField(verbose_name='date available')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='criticality',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.AddField(
            model_name='supplieritem',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainDash.item'),
        ),
        migrations.AddField(
            model_name='supplieritem',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainDash.supplier'),
        ),
    ]
