# Generated by Django 4.2.4 on 2023-08-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainDash', '0002_supplier_supplieritem_item_criticality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='location',
            field=models.CharField(default='', max_length=2),
        ),
    ]
