# Generated by Django 4.2.4 on 2023-08-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainDash', '0003_supplier_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='naics_code',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='delay_risk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='quality',
            field=models.IntegerField(default=0),
        ),
    ]
