# Generated by Django 4.2.4 on 2023-08-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainDash', '0005_coordenadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='lat',
            field=models.FloatField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='lon',
            field=models.FloatField(default=0, max_length=20),
        ),
    ]
