# Generated by Django 4.2.4 on 2023-08-23 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainDash', '0006_supplier_lat_supplier_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenadas',
            name='supplier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainDash.supplier'),
            preserve_default=False,
        ),
    ]
