# Generated by Django 4.2.4 on 2023-08-23 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainDash', '0008_alter_coordenadas_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenadas',
            name='supplier',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainDash.supplier'),
        ),
    ]
