# Generated by Django 5.2.7 on 2026-02-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainDash", "0002_legacy_migrations_replaced"),
    ]

    operations = [
        migrations.AddField(
            model_name="case_system",
            name="system_node_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="component",
            name="node_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="componentsupplier",
            name="edge_type",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="componentsupplier",
            name="is_selected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="componentsupplier",
            name="supplier_node_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="material",
            name="node_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="materialsupplier",
            name="edge_type",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="materialsupplier",
            name="is_selected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="materialsupplier",
            name="supplier_node_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="part",
            name="node_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="partsupplier",
            name="edge_type",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="partsupplier",
            name="is_selected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="partsupplier",
            name="supplier_node_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=120),
        ),
    ]
